version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: KraysaFinance